### ISSUE TITLE
❌ Bug report: player-config help menu image inaccurate

### ISSUE THREAD

**Issue by soupcantrolling** [Reishimanfr/The-World-Machine-Bot#12]
the player-config help menu image is inaccurate
/help -> player-config -> observe the image being the /avatar image

![image](https://github.com/Reishimanfr/The-World-Machine-Bot/assets/104684447/457e360f-58c0-4947-b388-17d0da60dfdd)

**Comment by Reishimanfr** [comment]
Resolved with v1.8.0 (https://github.com/Reishimanfr/The-World-Machine-Bot/commit/bd6b3fd0afb549298ac99e1a3adb48a16d8ffdbe)
