### ISSUE TITLE
❌ Bug: three billion message

### ISSUE THREAD

**Issue by soupcantrolling** [Reishimanfr/The-World-Machine-Bot#13]
whatever the hell this was lol

![image](https://github.com/Reishimanfr/The-World-Machine-Bot/assets/104684447/94775cd0-fb37-4e35-9666-7419d7f6c71a)

was just playing around putting music, since it didnt work i disconnected it and it kept doing this, disconnect command didn work further as it thought it was on a vc i wasnt on when it was in no other vc

**Comment by Reishimanfr** [comment]
I have **no fucking idea** why this happens. I believe it could be related to how I handle initial messages for the player status, but I'm not really sure. I'll look into it with ver. 1.8.0

**Comment by Reishimanfr** [comment]
This is ***possibly*** fixed alongside v1.8.0 but I'm not sure what could be causing it. If the issue persists I'll try looking further into it but for now, I'll close the issue.

**Comment by soupcantrolling** [comment]
steamhappy
