### ISSUE TITLE
🐛 Bug (Self-host): 

### ISSUE THREAD

**Issue by 0adrian** [Reishimanfr/The-World-Machine-Bot#17]
### What platform are you hosting on?

Linux

### What version of Lavalink are you using?

v4 - fe62703cc94ee43c9426c564e8564d5086b8b1ee-SNAPSHOT

### What version of your runtime are you using

v18.19.0

### Describe the bug

YouTube playlists not working

### Steps to reproduce

/play https://www.youtube.com/playlist?list=PLFBHIu8sTMFKLxamcXnWmRmRhxWxmcsu6

followed by a "Interaction failed with error: Error [InteractionAlreadyReplied]: The reply to this interaction has already been sent or deferred." error

![1714135172](https://github.com/Reishimanfr/The-World-Machine-Bot/assets/90132573/edd4559b-4ea9-48f1-85c1-a8bbeb4dbb94)

**Comment by Reishimanfr** [comment]
Issue resolved. Turns out I incorrectly used `interaction.reply` instead of `interaction.editReply` while parsing playlists. Pull the new code and try again
