### ISSUE TITLE
🐛 Bug: Large Youtube Playlist makes the bot Unresponsive

### ISSUE THREAD

**Issue by Abhijith4124** [Reishimanfr/The-World-Machine-Bot#18]
### Describe the bug

Large Youtube Playlist makes the bot Unresponsive

### Steps to reproduce

Play a large playlist from youtube.

Eg: https://www.youtube.com/playlist?list=PLofOSodK8MRoEnNkpfP3Ftlve38jj14jB

No Response will be provided by the bot, it will join the vc but won't play any songs.

### Expected behavior

The bot plays the music in a queue.

**Comment by Reishimanfr** [comment]
Resolved. Turns out I forgot to push the new update (v2.4.3) to TWM after fixing this bug (see #17 )
