### ISSUE TITLE
Queue button doesn't work :(

### ISSUE THREAD

**Issue by River2763** [Reishimanfr/The-World-Machine-Bot#7]
yeah uh idk what else to say it just doesn't work
![image](https://github.com/Reishimanfr/TWM-bot/assets/59708717/9ab51f2f-1e93-48f2-afbf-e9be9435faac)

**Comment by Reishimanfr** [comment]
Related to changes in how the bot responds to button interactions. They aren't defered anymore yet the bot responds with `editReply` instead of `reply`

**Comment by Reishimanfr** [comment]
that was in fact not why the thing didn't work. something related to collectors broke and I'm really lazy so I just added a warning to use the / command instead 
![obraz](https://github.com/Reishimanfr/The-World-Machine-Bot/assets/92938606/cdd07cba-a251-4e13-bc22-0db236536ccf)
