### ISSUE TITLE
song progress can get over the song length, somehow

### ISSUE THREAD

**Issue by River2763** [Reishimanfr/The-World-Machine-Bot#8]
![image](https://github.com/Reishimanfr/TWM-bot/assets/59708717/7bb0c80c-d979-41f7-9a12-2d0119ac5cc4)

**Comment by Reishimanfr** [comment]
Related to how song progress is handled in the player update event. Progress is rounded up to the nearest number divisable by 5

**Comment by Reishimanfr** [comment]
Issue fixed, fix will be available with the release of v1.5.1
